language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.2
  - 7.3

env:
  - PHPCS=1 DEFAULT=1

jobs:
  include:
    - php: 5.4
      env: PHPCS=1 DEFAULT=0
    - php: 5.5
      env: PHPCS=1 DEFAULT=0
  exclude:
    - php: 5.4
      env: PHPCS=1 DEFAULT=1
    - php: 5.5
      env: PHPCS=1 DEFAULT=1

before_script:
  - composer self-update
  - composer install
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require squizlabs/php_codesniffer=*; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 --ignore=./src/Thirdparty/* ./src; fi"

notifications:
  email: false
